### ISSUE TITLE
Do this code is applicable for Detr?

### ISSUE THREAD

**Issue by zobeirraisi** [jw9730/ori-GIoU#2]

**Comment by jw9730** [comment]
Yes, but you will need to edit the code a little bit to include object categories. I suggest replacing the gIOU computation functions in the DETR codebase using the functions in this repository. Also please keep in mind that the code is not optimized and may result in an excessive runtime.

**Comment by zobeirraisi** [comment]
Thanks for your response,
Yes, I saw that It giving me an error for GPUs. How to make it runnable for GPUs or optimize it?

**Comment by jw9730** [comment]
Can you post the error messages? Running the computations on GPU (Ubuntu 18.04 and CUDA 10.1) made no errors for me.

**Comment by jw9730** [comment]
I've tested it again; my local updates to support CUDA were not applied to the code. The updates will be made within 24 hours.

**Comment by jw9730** [comment]
The code now supports CUDA. For use cases, please check `test.py`.
